<script lang="ts" setup>
definePageMeta({ middleware: ["admin-only"] })

const settings = ref({
  sessionSuffix: "Academic Session",
  termPreset: "ordinals",
  numberOfCAs: 1,
  scoreDistribution: {
    "1st": 10,
    "2nd": 10,
    "3rd": 10,
    exam: 70
  },
  subjectTags: ["Art", "Science"],
  autoGenerateStudentId: true,
  studentIdPrefix: "STU"
})

const showStudentIdInput = computed(() => settings.value.autoGenerateStudentId)
const numberOfCAs = computed(() => settings.value.numberOfCAs)

const termPresetOptions = [
  { label: "1st, 2nd and 3rd", value: "ordinals" },
  { label: "First, Second and Third", value: "verbertim" }
]

function handleSubmit(payload: any) {
  console.log(payload)
}
</script>

<template>
  <div class="w-full space-y-5">
    <!-- Heading -->
    <div class="space-y-2">
      <ui-heading :level="5">Academic Settings</ui-heading>
      <p class="text-sm text-muted-foreground">Manage the school related settings and preference</p>
      <UiSeparator />
    </div>

    <!-- Body Content -->
    <div class="w-full">
      <FormKit type="form" v-model="settings" :actions="false" @submit="handleSubmit">
        <fieldset class="md:max-w-md space-y-6">
          <FormKit
            type="text"
            name="sessionSuffix"
            label="Session Suffix"
            placeholder="e.g Academic Session"
            help="This is a text appended to the session names e.g (2024/2025 Session)"
          />

          <FormKit
            type="_select"
            name="termPreset"
            label="Term Preset"
            placeholder="Select a term preset"
            :options="termPresetOptions"
            help="Choose how you'd like your terms to be created"
          />

          <!-- Contains fields for CA and Exams -->
          <SettingsScoreDistributionInput v-model:caCount="numberOfCAs" />

          <FormKit
            type="_tags"
            name="subjectTags"
            label="Subject Tags"
            placeholder="Create tags for subjects"
            help="Subject tags are used to filter and manage subjects"
          />

          <FormKit
            type="checkbox"
            name="autoGenerateStudentId"
            label="Auto generate student IDs"
            help="Choose whether to generate student IDs automatically or manually"
          />

          <FormKit
            v-if="showStudentIdInput"
            type="text"
            name="studentIdPrefix"
            label="Student ID Prefix"
            placeholder="e.g STU"
            help="This is a text prepended to the autogenerated id e.g STU-2026-001"
            validation="required|alpha|length:2,5"
          />

          <UiButton type="submit" block text="Submit" class="h-10" />
        </fieldset>
      </FormKit>
    </div>
  </div>
</template>
