allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  vue-demi: true
minimumReleaseAgeExclude:
  - '@better-auth/core@1.6.15'
  - '@better-auth/drizzle-adapter@1.6.15'
  - '@better-auth/kysely-adapter@1.6.15'
  - '@better-auth/memory-adapter@1.6.15'
  - '@better-auth/mongo-adapter@1.6.15'
  - '@better-auth/prisma-adapter@1.6.15'
  - '@better-auth/telemetry@1.6.15'
  - better-auth@1.6.15
