export const nigerianFirstNames = [
  "Emeka",
  "Chukwudi",
  "Obinna",
  "Ifeanyi",
  "Chidera",
  "Onyekachi",
  "Adaeze",
  "Chisom",
  "Ugochi",
  "Amaka",
  "Nkechi",
  "Ngozi",
  "Chinyere",
  "Uchenna",
  "Kelechi",
  "Tochukwu",
  "Chibuike",
  "Chizaram",
  "Somtochukwu",
  "Ifeoma",
  "Bolu",
  "Tunde",
  "Seun",
  "Wale",
  "Femi",
  "Yemi",
  "Sola",
  "Kola",
  "Bisi",
  "Toyin",
  "Funke",
  "Shade",
  "Gbemi",
  "Lola",
  "Dami",
  "Temitope",
  "Taiwo",
  "Kehinde",
  "Adewale",
  "Adebayo",
  "Babatunde",
  "Olumide",
  "Rotimi",
  "Musa",
  "Ibrahim",
  "Abubakar",
  "Usman",
  "Suleiman",
  "Fatima",
  "Hauwa",
  "Aisha",
  "Zainab",
  "Hadiza",
  "Bilkisu",
  "Ramatu",
  "Aminu",
  "Garba",
  "Abdullahi",
  "Yakubu",
  "Idris",
  "Sani",
  "Lawal",
  "Haruna",
  "Bashir",
  "Ejike",
  "Ikenna",
  "Chukwuemeka",
  "Nnamdi",
  "Okechukwu",
  "Chinonso",
  "Adaora",
  "Oluchi",
  "Onyinye",
  "Mmesoma",
  "Tobechukwu",
  "Chukwuka"
]

export const nigerianLastNames = [
  "Okafor",
  "Nwosu",
  "Eze",
  "Obi",
  "Chukwu",
  "Nwachukwu",
  "Igwe",
  "Onwu",
  "Adesanya",
  "Adeyemi",
  "Okonkwo",
  "Achebe",
  "Nwoye",
  "Obiora",
  "Orji",
  "Balogun",
  "Adeyinka",
  "Afolabi",
  "Adeleke",
  "Ogundimu",
  "Akintola",
  "Olawale",
  "Fashola",
  "Adekunle",
  "Ajayi",
  "Ogundele",
  "Ogundipe",
  "Musa",
  "Ibrahim",
  "Usman",
  "Abdullahi",
  "Suleiman",
  "Garba",
  "Lawal",
  "Yusuf",
  "Aliyu",
  "Danladi",
  "Tanko",
  "Sani",
  "Idris",
  "Bello",
  "Nwankwo",
  "Ihejirika",
  "Okoro",
  "Onyia",
  "Ejiofor",
  "Anyanwu",
  "Maduka",
  "Ekwueme",
  "Obaseki",
  "Edosomwan",
  "Omoruyi",
  "Osagie",
  "Oyelaran",
  "Oyewole",
  "Oyedele",
  "Oyedeji",
  "Oyediran",
  "Oyeniyi"
]

export const classNames = ["JSS 1", "JSS 2", "JSS 3", "SSS 1", "SSS 2", "SSS 3"]

export const sessions = ["2025/2026 Academic Session"]

export const numberPrefixes = [
  "0703",
  "0706",
  "0802",
  "0803",
  "0805",
  "0806",
  "0807",
  "0808",
  "0809",
  "0810",
  "0811",
  "0812",
  "0813",
  "0814",
  "0815",
  "0816",
  "0817",
  "0818",
  "0819",
  "0901",
  "0902",
  "0903",
  "0904",
  "0905",
  "0906",
  "0907",
  "0908",
  "0909"
]

export const SUBJECTS = [
  // Core / Compulsory
  { name: "English Language", tags: ["core", "language"] },
  { name: "Mathematics", tags: ["core", "science"] },
  { name: "Civic Education", tags: ["core", "social"] },
  { name: "Computer Studies", tags: ["core", "technology"] },

  // Sciences
  { name: "Biology", tags: ["science"] },
  { name: "Chemistry", tags: ["science"] },
  { name: "Physics", tags: ["science"] },
  { name: "Further Mathematics", tags: ["science", "mathematics"] },
  { name: "Agricultural Science", tags: ["science", "vocational"] },
  { name: "Health Science", tags: ["science"] },

  // Arts & Humanities
  { name: "Literature in English", tags: ["arts", "language"] },
  { name: "Yoruba", tags: ["arts", "language"] },
  { name: "Igbo", tags: ["arts", "language"] },
  { name: "Hausa", tags: ["arts", "language"] },
  { name: "Christian Religious Studies", tags: ["arts", "religion"] },
  { name: "Islamic Religious Studies", tags: ["arts", "religion"] },
  { name: "History", tags: ["arts", "social"] },

  // Social Sciences
  { name: "Economics", tags: ["social", "commerce"] },
  { name: "Geography", tags: ["social", "science"] },
  { name: "Government", tags: ["social"] },
  { name: "Social Studies", tags: ["social"] },

  // Commercial
  { name: "Financial Accounting", tags: ["commerce"] },
  { name: "Commerce", tags: ["commerce"] },
  { name: "Book Keeping", tags: ["commerce"] },
  { name: "Office Practice", tags: ["commerce", "vocational"] },
  { name: "Store Management", tags: ["commerce", "vocational"] },

  // Vocational / Technical
  { name: "Technical Drawing", tags: ["technical", "vocational"] },
  { name: "Basic Technology", tags: ["technical", "vocational"] },
  { name: "Food and Nutrition", tags: ["vocational"] },
  { name: "Home Economics", tags: ["vocational"] },
  { name: "Physical and Health Education", tags: ["vocational"] },
  { name: "Fine Art", tags: ["arts", "vocational"] },
  { name: "Music", tags: ["arts", "vocational"] }
]
